name: PatMap Test Runners

on: 
  push:
    branches: ["main"]
    
jobs:
  my-job:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        release: [R2020b, R2021a, R2022a, ]
        
    name: Run MATLAB Script
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ matrix.release }}
