name: PatMap Test Runners

on: 
  push:
    branches: ["main"]
    
jobs:
  my-job:
    strategy:
      matrix:
        os: [ubuntu-latest]
        release: [R2021a]
        
    name: Run MATLAB Script
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ matrix.release }}
      - name: Run script
        uses: matlab-actions/run-command@v1
